{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "shippingservice.serviceAccountName" . }}
  labels:
{{ include "shippingservice.labels" . | nindent 4 }}
{{- end -}}
