{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "paymentservice.serviceAccountName" . }}
  labels:
{{ include "paymentservice.labels" . | nindent 4 }}
{{- end -}}
