{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cartservice.serviceAccountName" . }}
  labels:
{{ include "cartservice.labels" . | nindent 4 }}
{{- end -}}
