apiVersion: v1
kind: Service
metadata:
  name: {{ include "currencyservice.name" . }}
  labels:
    {{- include "currencyservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7000
      name: grpc
  selector:
    {{- include "currencyservice.selectorLabels" . | nindent 4 }}
